# Auto-generated file. Do not edit.
from __future__ import annotations

from .types import GameItem, ItemType


class AllItems:
    WIRELESS_POWER_TOWER = GameItem(name="Wireless Power Tower", id=2202, type=ItemType.LOGISTICS)
    WIND_TURBINE = GameItem(name="Wind Turbine", id=2203, type=ItemType.PRODUCTION)
    WATER_PUMP = GameItem(name="Water Pump", id=2306, type=ItemType.PRODUCTION)
    WATER = GameItem(name="Water", id=1000, type=ItemType.RESOURCE)
    VERTICAL_LAUNCHING_SILO = GameItem(name="Vertical Launching Silo", id=2312, type=ItemType.PRODUCTION)
    UNIVERSE_MATRIX = GameItem(name="Universe Matrix", id=6006, type=ItemType.MATRIX)
    UNIPOLAR_MAGNET = GameItem(name="Unipolar Magnet", id=1016, type=ItemType.RESOURCE)
    TRAFFIC_MONITOR = GameItem(name="Traffic Monitor", id=2030, type=ItemType.LOGISTICS)
    TITANIUM_ORE = GameItem(name="Titanium Ore", id=1004, type=ItemType.RESOURCE)
    TITANIUM_INGOT = GameItem(name="Titanium Ingot", id=1106, type=ItemType.MATERIAL)
    TITANIUM_GLASS = GameItem(name="Titanium Glass", id=1119, type=ItemType.MATERIAL)
    TITANIUM_CRYSTAL = GameItem(name="Titanium Crystal", id=1118, type=ItemType.MATERIAL)
    TITANIUM_AMMO_BOX = GameItem(name="Titanium Ammo Box", id=1602, type=ItemType.PRODUCT)
    TITANIUM_ALLOY = GameItem(name="Titanium Alloy", id=1107, type=ItemType.MATERIAL)
    THRUSTER = GameItem(name="Thruster", id=1405, type=ItemType.COMPONENT)
    THERMAL_POWER_PLANT = GameItem(name="Thermal Power Plant", id=2204, type=ItemType.PRODUCTION)
    TESLA_TOWER = GameItem(name="Tesla Tower", id=2201, type=ItemType.LOGISTICS)
    SUPPRESSING_CAPSULE = GameItem(name="Suppressing Capsule", id=1613, type=ItemType.PRODUCT)
    SUPERSONIC_MISSILE_SET = GameItem(name="Supersonic Missile Set", id=1610, type=ItemType.PRODUCT)
    SUPERALLOY_AMMO_BOX = GameItem(name="Superalloy Ammo Box", id=1603, type=ItemType.PRODUCT)
    SUPER_MAGNETIC_RING = GameItem(name="Super-Magnetic Ring", id=1205, type=ItemType.COMPONENT)
    SULFURIC_ACID = GameItem(name="Sulfuric Acid", id=1116, type=ItemType.MATERIAL)
    STRUCTURE_MATRIX = GameItem(name="Structure Matrix", id=6003, type=ItemType.MATRIX)
    STRANGE_MATTER = GameItem(name="Strange Matter", id=1127, type=ItemType.MATERIAL)
    STRANGE_ANNIHILATION_FUEL_ROD = GameItem(name="Strange Annihilation Fuel Rod", id=1804, type=ItemType.PRODUCT)
    STORAGE_TANK = GameItem(name="Storage Tank", id=2106, type=ItemType.LOGISTICS)
    STONE_BRICK = GameItem(name="Stone Brick", id=1108, type=ItemType.MATERIAL)
    STONE = GameItem(name="Stone", id=1005, type=ItemType.RESOURCE)
    STEEL = GameItem(name="Steel", id=1103, type=ItemType.MATERIAL)
    STALAGMITE_CRYSTAL = GameItem(name="Stalagmite Crystal", id=1015, type=ItemType.RESOURCE)
    SPRAY_COATER = GameItem(name="Spray Coater", id=2313, type=ItemType.PRODUCTION)
    SPLITTER = GameItem(name="Splitter", id=2020, type=ItemType.LOGISTICS)
    SPACE_WARPER = GameItem(name="Space Warper", id=1210, type=ItemType.COMPONENT)
    SORTER_MK_III = GameItem(name="Sorter MK.III", id=2013, type=ItemType.LOGISTICS)
    SORTER_MK_II = GameItem(name="Sorter MK.II", id=2012, type=ItemType.LOGISTICS)
    SORTER_MK_I = GameItem(name="Sorter MK.I", id=2011, type=ItemType.LOGISTICS)
    SOLAR_SAIL = GameItem(name="Solar Sail", id=1501, type=ItemType.PRODUCT)
    SOLAR_PANEL = GameItem(name="Solar Panel", id=2205, type=ItemType.PRODUCTION)
    SOIL_PILE = GameItem(name="Soil Pile", id=1099, type=ItemType.RESOURCE)
    SMALL_CARRIER_ROCKET = GameItem(name="Small Carrier Rocket", id=1503, type=ItemType.PRODUCT)
    SILICON_BASED_NEURON = GameItem(name="Silicon-Based Neuron", id=5202, type=ItemType.DARK_FOG)
    SILICON_ORE = GameItem(name="Silicon Ore", id=1003, type=ItemType.RESOURCE)
    SIGNAL_TOWER = GameItem(name="Signal Tower", id=3007, type=ItemType.DEFENSE)
    SHELL_SET = GameItem(name="Shell Set", id=1604, type=ItemType.PRODUCT)
    SELF_EVOLUTION_LAB = GameItem(name="Self-Evolution Lab", id=2902, type=ItemType.PRODUCTION)
    SATELLITE_SUBSTATION = GameItem(name="Satellite Substation", id=2212, type=ItemType.LOGISTICS)
    SR_PLASMA_TURRET = GameItem(name="SR Plasma Turret", id=3010, type=ItemType.TURRET)
    REINFORCED_THRUSTER = GameItem(name="Reinforced Thruster", id=1406, type=ItemType.COMPONENT)
    REFINED_OIL = GameItem(name="Refined Oil", id=1114, type=ItemType.MATERIAL)
    RE_COMPOSING_ASSEMBLER = GameItem(name="Re-Composing Assembler", id=2318, type=ItemType.PRODUCTION)
    RAY_RECEIVER = GameItem(name="Ray Receiver", id=2208, type=ItemType.PRODUCTION)
    QUANTUM_CHIP = GameItem(name="Quantum Chip", id=1305, type=ItemType.COMPONENT)
    QUANTUM_CHEMICAL_PLANT = GameItem(name="Quantum Chemical Plant", id=2317, type=ItemType.PRODUCTION)
    PROTOTYPE = GameItem(name="Prototype", id=5101, type=ItemType.PRODUCT)
    PROLIFERATOR_MK_III = GameItem(name="Proliferator Mk.III", id=1143, type=ItemType.MATERIAL)
    PROLIFERATOR_MK_II = GameItem(name="Proliferator Mk.II", id=1142, type=ItemType.MATERIAL)
    PROLIFERATOR_MK_I = GameItem(name="Proliferator Mk.I", id=1141, type=ItemType.MATERIAL)
    PROCESSOR = GameItem(name="Processor", id=1303, type=ItemType.COMPONENT)
    PRISM = GameItem(name="Prism", id=1111, type=ItemType.MATERIAL)
    PRECISION_DRONE = GameItem(name="Precision Drone", id=5102, type=ItemType.PRODUCT)
    PLASTIC = GameItem(name="Plastic", id=1115, type=ItemType.MATERIAL)
    PLASMA_TURRET = GameItem(name="Plasma Turret", id=3004, type=ItemType.TURRET)
    PLASMA_EXCITER = GameItem(name="Plasma Exciter", id=1401, type=ItemType.COMPONENT)
    PLASMA_CAPSULE = GameItem(name="Plasma Capsule", id=1607, type=ItemType.PRODUCT)
    PLANT_FUEL = GameItem(name="Plant Fuel", id=1031, type=ItemType.RESOURCE)
    PLANETARY_SHIELD_GENERATOR = GameItem(name="Planetary Shield Generator", id=3008, type=ItemType.DEFENSE)
    PLANETARY_LOGISTICS_STATION = GameItem(name="Planetary Logistics Station", id=2103, type=ItemType.LOGISTICS)
    PLANE_SMELTER = GameItem(name="Plane Smelter", id=2315, type=ItemType.PRODUCTION)
    PLANE_FILTER = GameItem(name="Plane Filter", id=1304, type=ItemType.COMPONENT)
    PILE_SORTER = GameItem(name="Pile Sorter", id=2014, type=ItemType.LOGISTICS)
    PHOTON_COMBINER = GameItem(name="Photon Combiner", id=1404, type=ItemType.COMPONENT)
    PARTICLE_CONTAINER = GameItem(name="Particle Container", id=1206, type=ItemType.COMPONENT)
    PARTICLE_BROADBAND = GameItem(name="Particle Broadband", id=1402, type=ItemType.COMPONENT)
    ORGANIC_CRYSTAL = GameItem(name="Organic Crystal", id=1117, type=ItemType.MATERIAL)
    ORBITAL_COLLECTOR = GameItem(name="Orbital Collector", id=2105, type=ItemType.LOGISTICS)
    OIL_REFINERY = GameItem(name="Oil Refinery", id=2308, type=ItemType.PRODUCTION)
    OIL_EXTRACTOR = GameItem(name="Oil Extractor", id=2307, type=ItemType.PRODUCTION)
    NEGENTROPY_SMELTER = GameItem(name="Negentropy Smelter", id=2319, type=ItemType.PRODUCTION)
    NEGENTROPY_SINGULARITY = GameItem(name="Negentropy Singularity", id=5204, type=ItemType.DARK_FOG)
    MISSILE_TURRET = GameItem(name="Missile Turret", id=3005, type=ItemType.TURRET)
    MISSILE_SET = GameItem(name="Missile Set", id=1609, type=ItemType.PRODUCT)
    MINING_MACHINE = GameItem(name="Mining Machine", id=2301, type=ItemType.PRODUCTION)
    MINIATURE_PARTICLE_COLLIDER = GameItem(name="Miniature Particle Collider", id=2310, type=ItemType.PRODUCTION)
    MINI_FUSION_POWER_PLANT = GameItem(name="Mini Fusion Power Plant", id=2211, type=ItemType.PRODUCTION)
    MICROCRYSTALLINE_COMPONENT = GameItem(name="Microcrystalline Component", id=1302, type=ItemType.COMPONENT)
    MATTER_RECOMBINATOR = GameItem(name="Matter Recombinator", id=5203, type=ItemType.DARK_FOG)
    MATRIX_LAB = GameItem(name="Matrix Lab", id=2901, type=ItemType.PRODUCTION)
    MAGNUM_AMMO_BOX = GameItem(name="Magnum Ammo Box", id=1601, type=ItemType.PRODUCT)
    MAGNETIC_COIL = GameItem(name="Magnetic Coil", id=1202, type=ItemType.COMPONENT)
    MAGNET = GameItem(name="Magnet", id=1102, type=ItemType.MATERIAL)
    LOGISTICS_DRONE = GameItem(name="Logistics Drone", id=5001, type=ItemType.LOGISTICS)
    LOGISTICS_DISTRIBUTOR = GameItem(name="Logistics Distributor", id=2107, type=ItemType.LOGISTICS)
    LOGISTICS_BOT = GameItem(name="Logistics Bot", id=5003, type=ItemType.LOGISTICS)
    LOG = GameItem(name="Log", id=1030, type=ItemType.RESOURCE)
    LASER_TURRET = GameItem(name="Laser Turret", id=3002, type=ItemType.TURRET)
    KIMBERLITE_ORE = GameItem(name="Kimberlite Ore", id=1012, type=ItemType.RESOURCE)
    JAMMING_CAPSULE = GameItem(name="Jamming Capsule", id=1612, type=ItemType.PRODUCT)
    JAMMER_TOWER = GameItem(name="Jammer Tower", id=3006, type=ItemType.TURRET)
    IRON_ORE = GameItem(name="Iron Ore", id=1001, type=ItemType.RESOURCE)
    IRON_INGOT = GameItem(name="Iron Ingot", id=1101, type=ItemType.MATERIAL)
    INTERSTELLAR_LOGISTICS_VESSEL = GameItem(name="Interstellar Logistics Vessel", id=5002, type=ItemType.LOGISTICS)
    INTERSTELLAR_LOGISTICS_STATION = GameItem(name="Interstellar Logistics Station", id=2104, type=ItemType.LOGISTICS)
    INFORMATION_MATRIX = GameItem(name="Information Matrix", id=6004, type=ItemType.MATRIX)
    IMPLOSION_CANNON = GameItem(name="Implosion Cannon", id=3003, type=ItemType.TURRET)
    HYDROGEN_FUEL_ROD = GameItem(name="Hydrogen Fuel Rod", id=1801, type=ItemType.PRODUCT)
    HYDROGEN = GameItem(name="Hydrogen", id=1120, type=ItemType.MATERIAL)
    HIGH_PURITY_SILICON = GameItem(name="High-Purity Silicon", id=1105, type=ItemType.MATERIAL)
    HIGH_EXPLOSIVE_SHELL_SET = GameItem(name="High-Explosive Shell Set", id=1605, type=ItemType.PRODUCT)
    GRAVITY_MISSILE_SET = GameItem(name="Gravity Missile Set", id=1611, type=ItemType.PRODUCT)
    GRAVITY_MATRIX = GameItem(name="Gravity Matrix", id=6005, type=ItemType.MATRIX)
    GRAVITON_LENS = GameItem(name="Graviton Lens", id=1209, type=ItemType.COMPONENT)
    GRATING_CRYSTAL = GameItem(name="Grating Crystal", id=1014, type=ItemType.RESOURCE)
    GRAPHENE = GameItem(name="Graphene", id=1123, type=ItemType.MATERIAL)
    GLASS = GameItem(name="Glass", id=1110, type=ItemType.MATERIAL)
    GEOTHERMAL_POWER_STATION = GameItem(name="Geothermal Power Station", id=2213, type=ItemType.PRODUCTION)
    GEAR = GameItem(name="Gear", id=1201, type=ItemType.COMPONENT)
    GAUSS_TURRET = GameItem(name="Gauss Turret", id=3001, type=ItemType.TURRET)
    FRAME_MATERIAL = GameItem(name="Frame Material", id=1125, type=ItemType.MATERIAL)
    FRACTIONATOR = GameItem(name="Fractionator", id=2314, type=ItemType.PRODUCTION)
    FRACTAL_SILICON = GameItem(name="Fractal Silicon", id=1013, type=ItemType.RESOURCE)
    FOUNDATION = GameItem(name="Foundation", id=1131, type=ItemType.COMPONENT)
    FIRE_ICE = GameItem(name="Fire Ice", id=1011, type=ItemType.RESOURCE)
    EXPLOSIVE_UNIT = GameItem(name="Explosive Unit", id=1129, type=ItemType.COMPONENT)
    ENGINE = GameItem(name="Engine", id=1407, type=ItemType.COMPONENT)
    ENERGY_SHARD = GameItem(name="Energy Shard", id=5206, type=ItemType.DARK_FOG)
    ENERGY_MATRIX = GameItem(name="Energy Matrix", id=6002, type=ItemType.MATRIX)
    ENERGY_EXCHANGER = GameItem(name="Energy Exchanger", id=2209, type=ItemType.LOGISTICS)
    ENERGETIC_GRAPHITE = GameItem(name="Energetic Graphite", id=1109, type=ItemType.MATERIAL)
    ELECTROMAGNETIC_TURBINE = GameItem(name="Electromagnetic Turbine", id=1204, type=ItemType.COMPONENT)
    ELECTROMAGNETIC_MATRIX = GameItem(name="Electromagnetic Matrix", id=6001, type=ItemType.MATRIX)
    ELECTRIC_MOTOR = GameItem(name="Electric Motor", id=1203, type=ItemType.COMPONENT)
    EM_RAIL_EJECTOR = GameItem(name="EM-Rail Ejector", id=2311, type=ItemType.PRODUCTION)
    DYSON_SPHERE_COMPONENT = GameItem(name="Dyson Sphere Component", id=1502, type=ItemType.COMPONENT)
    DIAMOND = GameItem(name="Diamond", id=1112, type=ItemType.MATERIAL)
    DEUTERON_FUEL_ROD = GameItem(name="Deuteron Fuel Rod", id=1802, type=ItemType.PRODUCT)
    DEUTERIUM = GameItem(name="Deuterium", id=1121, type=ItemType.MATERIAL)
    DESTROYER = GameItem(name="Destroyer", id=5112, type=ItemType.PRODUCT)
    DEPOT_MK_II = GameItem(name="Depot MK.II", id=2102, type=ItemType.LOGISTICS)
    DEPOT_MK_I = GameItem(name="Depot MK.I", id=2101, type=ItemType.LOGISTICS)
    DARK_FOG_MATRIX = GameItem(name="Dark Fog Matrix", id=5201, type=ItemType.DARK_FOG)
    CRYSTAL_SILICON = GameItem(name="Crystal Silicon", id=1113, type=ItemType.MATERIAL)
    CRYSTAL_SHELL_SET = GameItem(name="Crystal Shell Set", id=1606, type=ItemType.PRODUCT)
    CRYSTAL_EXPLOSIVE_UNIT = GameItem(name="Crystal Explosive Unit", id=1130, type=ItemType.COMPONENT)
    CRUDE_OIL = GameItem(name="Crude Oil", id=1007, type=ItemType.RESOURCE)
    CRITICAL_PHOTON = GameItem(name="Critical Photon", id=1208, type=ItemType.MATERIAL)
    CORVETTE = GameItem(name="Corvette", id=5111, type=ItemType.PRODUCT)
    CORE_ELEMENT = GameItem(name="Core Element", id=5205, type=ItemType.DARK_FOG)
    COPPER_ORE = GameItem(name="Copper Ore", id=1002, type=ItemType.RESOURCE)
    COPPER_INGOT = GameItem(name="Copper Ingot", id=1104, type=ItemType.MATERIAL)
    CONVEYOR_BELT_MK_III = GameItem(name="Conveyor Belt MK.III", id=2003, type=ItemType.LOGISTICS)
    CONVEYOR_BELT_MK_II = GameItem(name="Conveyor Belt MK.II", id=2002, type=ItemType.LOGISTICS)
    CONVEYOR_BELT_MK_I = GameItem(name="Conveyor Belt MK.I", id=2001, type=ItemType.LOGISTICS)
    COMBUSTIBLE_UNIT = GameItem(name="Combustible Unit", id=1128, type=ItemType.COMPONENT)
    COAL = GameItem(name="Coal", id=1006, type=ItemType.RESOURCE)
    CIRCUIT_BOARD = GameItem(name="Circuit Board", id=1301, type=ItemType.COMPONENT)
    CHEMICAL_PLANT = GameItem(name="Chemical Plant", id=2309, type=ItemType.PRODUCTION)
    CASIMIR_CRYSTAL = GameItem(name="Casimir Crystal", id=1126, type=ItemType.MATERIAL)
    CARBON_NANOTUBE = GameItem(name="Carbon Nanotube", id=1124, type=ItemType.MATERIAL)
    BATTLEFIELD_ANALYSIS_BASE = GameItem(name="Battlefield Analysis Base", id=3009, type=ItemType.DEFENSE)
    AUTOMATIC_PILER = GameItem(name="Automatic Piler", id=2040, type=ItemType.LOGISTICS)
    ATTACK_DRONE = GameItem(name="Attack Drone", id=5103, type=ItemType.PRODUCT)
    ASSEMBLING_MACHINE_MK_III = GameItem(name="Assembling Machine Mk.III", id=2305, type=ItemType.PRODUCTION)
    ASSEMBLING_MACHINE_MK_II = GameItem(name="Assembling Machine Mk.II", id=2304, type=ItemType.PRODUCTION)
    ASSEMBLING_MACHINE_MK_I = GameItem(name="Assembling Machine Mk.I", id=2303, type=ItemType.PRODUCTION)
    ARTIFICIAL_STAR = GameItem(name="Artificial Star", id=2210, type=ItemType.PRODUCTION)
    ARC_SMELTER = GameItem(name="Arc Smelter", id=2302, type=ItemType.PRODUCTION)
    ANTIMATTER_FUEL_ROD = GameItem(name="Antimatter Fuel Rod", id=1803, type=ItemType.PRODUCT)
    ANTIMATTER_CAPSULE = GameItem(name="Antimatter Capsule", id=1608, type=ItemType.PRODUCT)
    ANTIMATTER = GameItem(name="Antimatter", id=1122, type=ItemType.MATERIAL)
    ANNIHILATION_CONSTRAINT_SPHERE = GameItem(name="Annihilation Constraint Sphere", id=1403, type=ItemType.COMPONENT)
    ADVANCED_MINING_MACHINE = GameItem(name="Advanced Mining Machine", id=2316, type=ItemType.PRODUCTION)
    ACCUMULATOR_FULL = GameItem(name="Accumulator (Full)", id=2207, type=ItemType.LOGISTICS)
    ACCUMULATOR = GameItem(name="Accumulator", id=2206, type=ItemType.LOGISTICS)


class BuildingItems:
    WIRELESS_POWER_TOWER = GameItem(name="Wireless Power Tower", id=2202, type=ItemType.LOGISTICS)
    WIND_TURBINE = GameItem(name="Wind Turbine", id=2203, type=ItemType.PRODUCTION)
    WATER_PUMP = GameItem(name="Water Pump", id=2306, type=ItemType.PRODUCTION)
    VERTICAL_LAUNCHING_SILO = GameItem(name="Vertical Launching Silo", id=2312, type=ItemType.PRODUCTION)
    TRAFFIC_MONITOR = GameItem(name="Traffic Monitor", id=2030, type=ItemType.LOGISTICS)
    THERMAL_POWER_PLANT = GameItem(name="Thermal Power Plant", id=2204, type=ItemType.PRODUCTION)
    TESLA_TOWER = GameItem(name="Tesla Tower", id=2201, type=ItemType.LOGISTICS)
    STORAGE_TANK = GameItem(name="Storage Tank", id=2106, type=ItemType.LOGISTICS)
    SPRAY_COATER = GameItem(name="Spray Coater", id=2313, type=ItemType.PRODUCTION)
    SPLITTER = GameItem(name="Splitter", id=2020, type=ItemType.LOGISTICS)
    SORTER_MK_III = GameItem(name="Sorter MK.III", id=2013, type=ItemType.LOGISTICS)
    SORTER_MK_II = GameItem(name="Sorter MK.II", id=2012, type=ItemType.LOGISTICS)
    SORTER_MK_I = GameItem(name="Sorter MK.I", id=2011, type=ItemType.LOGISTICS)
    SOLAR_PANEL = GameItem(name="Solar Panel", id=2205, type=ItemType.PRODUCTION)
    SIGNAL_TOWER = GameItem(name="Signal Tower", id=3007, type=ItemType.DEFENSE)
    SELF_EVOLUTION_LAB = GameItem(name="Self-Evolution Lab", id=2902, type=ItemType.PRODUCTION)
    SATELLITE_SUBSTATION = GameItem(name="Satellite Substation", id=2212, type=ItemType.LOGISTICS)
    SR_PLASMA_TURRET = GameItem(name="SR Plasma Turret", id=3010, type=ItemType.TURRET)
    RE_COMPOSING_ASSEMBLER = GameItem(name="Re-Composing Assembler", id=2318, type=ItemType.PRODUCTION)
    RAY_RECEIVER = GameItem(name="Ray Receiver", id=2208, type=ItemType.PRODUCTION)
    QUANTUM_CHEMICAL_PLANT = GameItem(name="Quantum Chemical Plant", id=2317, type=ItemType.PRODUCTION)
    PLASMA_TURRET = GameItem(name="Plasma Turret", id=3004, type=ItemType.TURRET)
    PLANETARY_SHIELD_GENERATOR = GameItem(name="Planetary Shield Generator", id=3008, type=ItemType.DEFENSE)
    PLANETARY_LOGISTICS_STATION = GameItem(name="Planetary Logistics Station", id=2103, type=ItemType.LOGISTICS)
    PLANE_SMELTER = GameItem(name="Plane Smelter", id=2315, type=ItemType.PRODUCTION)
    PILE_SORTER = GameItem(name="Pile Sorter", id=2014, type=ItemType.LOGISTICS)
    ORBITAL_COLLECTOR = GameItem(name="Orbital Collector", id=2105, type=ItemType.LOGISTICS)
    OIL_REFINERY = GameItem(name="Oil Refinery", id=2308, type=ItemType.PRODUCTION)
    OIL_EXTRACTOR = GameItem(name="Oil Extractor", id=2307, type=ItemType.PRODUCTION)
    NEGENTROPY_SMELTER = GameItem(name="Negentropy Smelter", id=2319, type=ItemType.PRODUCTION)
    MISSILE_TURRET = GameItem(name="Missile Turret", id=3005, type=ItemType.TURRET)
    MINING_MACHINE = GameItem(name="Mining Machine", id=2301, type=ItemType.PRODUCTION)
    MINIATURE_PARTICLE_COLLIDER = GameItem(name="Miniature Particle Collider", id=2310, type=ItemType.PRODUCTION)
    MINI_FUSION_POWER_PLANT = GameItem(name="Mini Fusion Power Plant", id=2211, type=ItemType.PRODUCTION)
    MATRIX_LAB = GameItem(name="Matrix Lab", id=2901, type=ItemType.PRODUCTION)
    LOGISTICS_DRONE = GameItem(name="Logistics Drone", id=5001, type=ItemType.LOGISTICS)
    LOGISTICS_DISTRIBUTOR = GameItem(name="Logistics Distributor", id=2107, type=ItemType.LOGISTICS)
    LOGISTICS_BOT = GameItem(name="Logistics Bot", id=5003, type=ItemType.LOGISTICS)
    LASER_TURRET = GameItem(name="Laser Turret", id=3002, type=ItemType.TURRET)
    JAMMER_TOWER = GameItem(name="Jammer Tower", id=3006, type=ItemType.TURRET)
    INTERSTELLAR_LOGISTICS_VESSEL = GameItem(name="Interstellar Logistics Vessel", id=5002, type=ItemType.LOGISTICS)
    INTERSTELLAR_LOGISTICS_STATION = GameItem(name="Interstellar Logistics Station", id=2104, type=ItemType.LOGISTICS)
    IMPLOSION_CANNON = GameItem(name="Implosion Cannon", id=3003, type=ItemType.TURRET)
    GEOTHERMAL_POWER_STATION = GameItem(name="Geothermal Power Station", id=2213, type=ItemType.PRODUCTION)
    GAUSS_TURRET = GameItem(name="Gauss Turret", id=3001, type=ItemType.TURRET)
    FRACTIONATOR = GameItem(name="Fractionator", id=2314, type=ItemType.PRODUCTION)
    ENERGY_EXCHANGER = GameItem(name="Energy Exchanger", id=2209, type=ItemType.LOGISTICS)
    EM_RAIL_EJECTOR = GameItem(name="EM-Rail Ejector", id=2311, type=ItemType.PRODUCTION)
    DEPOT_MK_II = GameItem(name="Depot MK.II", id=2102, type=ItemType.LOGISTICS)
    DEPOT_MK_I = GameItem(name="Depot MK.I", id=2101, type=ItemType.LOGISTICS)
    CONVEYOR_BELT_MK_III = GameItem(name="Conveyor Belt MK.III", id=2003, type=ItemType.LOGISTICS)
    CONVEYOR_BELT_MK_II = GameItem(name="Conveyor Belt MK.II", id=2002, type=ItemType.LOGISTICS)
    CONVEYOR_BELT_MK_I = GameItem(name="Conveyor Belt MK.I", id=2001, type=ItemType.LOGISTICS)
    CHEMICAL_PLANT = GameItem(name="Chemical Plant", id=2309, type=ItemType.PRODUCTION)
    BATTLEFIELD_ANALYSIS_BASE = GameItem(name="Battlefield Analysis Base", id=3009, type=ItemType.DEFENSE)
    AUTOMATIC_PILER = GameItem(name="Automatic Piler", id=2040, type=ItemType.LOGISTICS)
    ASSEMBLING_MACHINE_MK_III = GameItem(name="Assembling Machine Mk.III", id=2305, type=ItemType.PRODUCTION)
    ASSEMBLING_MACHINE_MK_II = GameItem(name="Assembling Machine Mk.II", id=2304, type=ItemType.PRODUCTION)
    ASSEMBLING_MACHINE_MK_I = GameItem(name="Assembling Machine Mk.I", id=2303, type=ItemType.PRODUCTION)
    ARTIFICIAL_STAR = GameItem(name="Artificial Star", id=2210, type=ItemType.PRODUCTION)
    ARC_SMELTER = GameItem(name="Arc Smelter", id=2302, type=ItemType.PRODUCTION)
    ADVANCED_MINING_MACHINE = GameItem(name="Advanced Mining Machine", id=2316, type=ItemType.PRODUCTION)
    ACCUMULATOR_FULL = GameItem(name="Accumulator (Full)", id=2207, type=ItemType.LOGISTICS)
    ACCUMULATOR = GameItem(name="Accumulator", id=2206, type=ItemType.LOGISTICS)
